// <auto-generated />
namespace Lidia.Scheduler.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBInitialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBInitialization));
        
        string IMigrationMetadata.Id
        {
            get { return "201901062130051_DB-Initialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
